- name: add repo ppa:nginx
  apt_repository: repo="deb http://nginx.org/packages/ubuntu/ precise nginx"

- name: add key ppa:nginx
  apt_key: url="http://nginx.org/keys/nginx_signing.key"  state=present

- apt: update_cache=yes

- name: install
  apt: name=nginx

- name: configure
  template:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf

- file: path=/etc/nginx/conf.d/default state=absent

- lineinfile:
    dest: '/etc/nginx/nginx.conf'
    regexp: 'user www-data;'
    line: 'user vagrant;'
    backrefs: yes

- name:  restart
  service:
    name: nginx
    state: restarted