- hosts: webservers
  sudo: yes
  gather_facts: no
  vars:
    - mysql_root_password: "******"
  roles:
  - { role: started }
  - { role: mongodb }
  - { role: projects }
  - { role: nginx }
  - { role: python }
  - { role: mysql }
  - { role: php5 }
  - { role: applications }