- name: install
  apt: pkg={{ item }}
  with_items:
    - mysql-server
    - mysql-client

- lineinfile:
    dest: '/etc/mysql/my.cnf'
    regexp: 'user[\s]+\=[\s]+mysql'
    line: 'user = root'
    backrefs: yes

- name: restart
  shell: service mysql restart

- name: Create tables from dumps
  command: python /projects/scripts/create_tables_from_dumps.py